name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm

      - name: Set up Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish package on NPM 📦
        run: npm version  ${{github.ref_name}} --allow-same-version --allow-empty && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
