name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests
        run: npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
